[package]
name = "test_client"
version = "0.1.0"
edition = "2024"

[dependencies]
openh264 = "0.8.1"
winit = "0.30.12"
pixels = "0.15.0"
once_cell = "1.21.3"
rtp = "0.14.0"
webrtc-util = "0.12.0"
ffmpeg-next = "^8.0.0"