[target.x86_64-pc-windows-msvc.env]
FFMPEG_DIR = "C:/Program Files/ffmpeg"
PKG_CONFIG_PATH = "C:/Program Files/ffmpeg/lib/pkgconfig"

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "link-arg=/LIBPATH:C:/Program Files/ffmpeg/lib"]
