name: Rust

on:
  push:
    branches: [ "main", "develop" ] 
  pull_request:
    branches: [ "main", "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Client
      working-directory: ./Client
      run: cargo build --verbose
  build-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Server
      working-directory: ./Server/src-tauri
      run: cargo build --verbose

